---

- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

    - name: check if nginx is installed
      shell: "which nginx"
      register: result
      ignore_errors: yes

    - name: skip installation
      meta:
       name: end_host
       when: result.false is false
   
    - name: update cache
      apt:
       update_cache: yes
       upgrade: yes

    - name: install nginx
      apt:
       name: nginx
       state: present

    - name: start nginx
      service:
       name: nginx
       state: started


    - name: "create www directory"
      file:
       path: /var/www/{{ your_domain_name }}
       state: directory
       mode: '0775'
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"

    - name: Copy Sample html file 
      copy:
        src: index.html
        dest: /var/www/{{ your_domain_name }}
        mode: preserve

    - name: Apply Nginx template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp